In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import re
import nltk
from nltk.corpus import stopwords
import pandas as pd
import pickle
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sentence_transformers import SentenceTransformer
import warnings
warnings.filterwarnings('ignore')

# Exploring dataset

In [ ]:
df=pd.read_csv("CourseraDataset-Unclean.csv")

In [ ]:
df.head()

,Course Title,Rating,Level,Duration,Schedule,Review,What you will learn,Skill gain,Modules,Instructor,Offered By,Keyword,Course Url
0,Fashion as Design,4.8,Beginner level,20 hours (approximately),Flexible schedule,"2,813 reviews",NaN,"['Art History', 'Art', 'History', 'Creativity']","['Introduction', 'Heroes', 'Silhouettes', 'Cou...","['Anna Burckhardt', 'Paola Antonelli', 'Michel...",['The Museum of Modern Art'],Arts and Humanities,https://www.coursera.org/learn/fashion-design
1,Modern American Poetry,4.4,Beginner level,Approx. 34 hours to complete,Flexible schedule,100 reviews,NaN,[],"['Orientation', 'Module 1', 'Module 2', 'Modul...",['Cary Nelson'],['University of Illinois at Urbana-Champaign'],Arts and Humanities,https://www.coursera.org/learn/modern-american...
2,Pixel Art for Video Games,4.5,Beginner level,9 hours (approximately),Flexible schedule,227 reviews,NaN,[],"['Week 1: Introduction to Pixel Art', 'Week 2:...","['Andrew Dennis', 'Ricardo Guimaraes']",['Michigan State University'],Arts and Humanities,https://www.coursera.org/learn/pixel-art-video...
3,Distribución digital de la música independiente,NaN,Beginner level,Approx. 8 hours to complete,Flexible schedule,NaN,NaN,[],"['Semana 1', 'Semana 2', 'Semana 3', 'Semana 4']",['Eduardo de la Vara Brown.'],['SAE Institute México'],Arts and Humanities,https://www.coursera.org/learn/distribucion-di...
4,The Blues: Understanding and Performing an Ame...,4.8,Beginner level,Approx. 11 hours to complete,Flexible schedule,582 reviews,Students will be able to describe the blues as...,"['Music', 'Chord', 'Jazz', 'Jazz Improvisation']","['Blues Progressions – Theory and Practice ', ...",['Dariusz Terefenko'],['University of Rochester'],Arts and Humanities,https://www.coursera.org/learn/the-blues

In [ ]:
df.columns

Index(['Course Title', 'Rating', 'Level', 'Duration', 'Schedule', 'Review',
       'What you will learn', 'Skill gain', 'Modules', 'Instructor',
       'Offered By', 'Keyword', 'Course Url'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9595 entries, 0 to 9594
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Course Title         9595 non-null   object
 1   Rating               8156 non-null   float64
 2   Level                8330 non-null   object
 3   Duration             9333 non-null   object
 4   Schedule             8912 non-null   object
 5   Review               8152 non-null   object
 6   What you will learn  4984 non-null   object
 7   Skill gain           9595 non-null   object
 8   Modules              9595 non-null   object
 9   Instructor           9595 non-null   object
 10  Offered By           9595 non-null   object
 11  Keyword              9595 non-null   object
 12  Course Url           9595 non-null   object
dtypes: float64(1), object(12)
memory usage: 974.6+ KB

In [ ]:
df.shape

(9595, 13)

In [ ]:
df.isnull().sum()

Course Title              0
Rating                 1439
Level                  1265
Duration                262
Schedule                683
Review                 1443
What you will learn    4611
Skill gain                0
Modules                   0
Instructor                0
Offered By                0
Keyword                   0
Course Url                0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(900)

# Data Preprocessing

In [ ]:
required_columns = [

    "Course Title",

    "Rating",

    "Level",

    "Duration",

    "Review",

    "What you will learn",

    "Skill gain",

    "Modules",

    "Instructor",

    "Offered By",

    "Keyword",

    "Course Url"
]
df = df[required_columns]

In [ ]:
df = df.rename(columns={

    "Course Title": "title",

    "Rating": "rating",

    "Level": "level",

    "Duration": "duration",

    "Review": "review",

    "What you will learn": "description",

    "Skill gain": "skills",

    "Modules": "modules",

    "Instructor": "instructor",

    "Offered By": "platform",

    "Keyword": "category",

    "Course Url": "url"
})

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.fillna("", inplace=True)

In [ ]:
df.reset_index(drop=True, inplace=True)

In [ ]:
df.shape

(8695, 12)

In [ ]:
print(df.isnull().sum())

title          0
rating         0
level          0
duration       0
review         0
description    0
skills         0
modules        0
instructor     0
platform       0
category       0
url            0
dtype: int64

In [ ]:
df.head()

,title,rating,level,duration,review,description,skills,modules,instructor,platform,category,url
0,Fashion as Design,4.8,Beginner level,20 hours (approximately),"2,813 reviews",,"['Art History', 'Art', 'History', 'Creativity']","['Introduction', 'Heroes', 'Silhouettes', 'Cou...","['Anna Burckhardt', 'Paola Antonelli', 'Michel...",['The Museum of Modern Art'],Arts and Humanities,https://www.coursera.org/learn/fashion-design
1,Modern American Poetry,4.4,Beginner level,Approx. 34 hours to complete,100 reviews,,[],"['Orientation', 'Module 1', 'Module 2', 'Modul...",['Cary Nelson'],['University of Illinois at Urbana-Champaign'],Arts and Humanities,https://www.coursera.org/learn/modern-american...
2,Pixel Art for Video Games,4.5,Beginner level,9 hours (approximately),227 reviews,,[],"['Week 1: Introduction to Pixel Art', 'Week 2:...","['Andrew Dennis', 'Ricardo Guimaraes']",['Michigan State University'],Arts and Humanities,https://www.coursera.org/learn/pixel-art-video...
3,Distribución digital de la música independiente,,Beginner level,Approx. 8 hours to complete,,,[],"['Semana 1', 'Semana 2', 'Semana 3', 'Semana 4']",['Eduardo de la Vara Brown.'],['SAE Institute México'],Arts and Humanities,https://www.coursera.org/learn/distribucion-di...
4,The Blues: Understanding and Performing an Ame...,4.8,Beginner level,Approx. 11 hours to complete,582 reviews,Students will be able to describe the blues as...,"['Music', 'Chord', 'Jazz', 'Jazz Improvisation']","['Blues Progressions – Theory and Practice ', ...",['Dariusz Terefenko'],['University of Rochester'],Arts and Humanities,https://www.coursera.org/learn/the-blues

# NLP Feature Engineering & Text Preprocessing

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [ ]:
df["combined_features"] = (

    df["title"] + " " +

    df["description"] + " " +

    df["skills"] + " " +

    df["modules"] + " " +

    df["category"]
)

In [ ]:
stop_words = set(stopwords.words('english'))

In [ ]:
import unicodedata
import re

def clean_text(text):

    # Convert to string
    text = str(text)

    # Lowercase
    text = text.lower()

    # Normalize accented characters
    text = unicodedata.normalize('NFKD', text)

    text = text.encode('ascii', 'ignore').decode('utf-8')

    # Remove URLs
    text = re.sub(r"http\S+", "", text)

    # Remove special characters
    text = re.sub(r"[^a-zA-Z ]", " ", text)

    # Remove extra spaces
    text = re.sub(r"\s+", " ", text)

    # Strip spaces
    text = text.strip()

    return text

In [ ]:
df["combined_features"] = df["combined_features"].apply(clean_text)

In [ ]:
print(df[["title", "combined_features"]].head())

                                               title  \
0                                  Fashion as Design
1                             Modern American Poetry
2                          Pixel Art for Video Games
3    Distribución digital de la música independiente
4  The Blues: Understanding and Performing an Ame...

                                   combined_features
0  fashion as design art history art history crea...
1  modern american poetry orientation module modu...
2  pixel art for video games week introduction to...
3  distribucion digital de la musica independient...
4  the blues understanding and performing an amer...

# TF-IDF Recommendation Engine

In [ ]:
tfidf = TfidfVectorizer(
    max_features=5000,
    stop_words='english'
)

In [ ]:
tfidf_matrix = tfidf.fit_transform(df["combined_features"])

In [ ]:
similarity_matrix = cosine_similarity(tfidf_matrix)

In [ ]:
print("TF-IDF Shape:", tfidf_matrix.shape)

TF-IDF Shape: (8695, 5000)

In [ ]:
print("Similarity Matrix Shape:", similarity_matrix.shape)

Similarity Matrix Shape: (8695, 8695)

In [ ]:
with open("tfidf_vectorizer.pkl", "wb") as f:
    pickle.dump(tfidf, f)

In [ ]:
with open("tfidf_matrix.pkl", "wb") as f:
    pickle.dump(tfidf_matrix, f)

# Recommendation Function

In [ ]:
def recommend_courses(user_input, top_n=5):

    # Query embedding
    query_embedding = model.encode([user_input])

    # Similarity scores
    similarity_scores = cosine_similarity(

        query_embedding,

        course_embeddings
    )

    # Flatten
    similarity_scores = similarity_scores.flatten()

    # Sorted indices
    sorted_indices = similarity_scores.argsort()[::-1]

    # Store unique titles
    recommended_titles = set()

    print("\nRecommended Courses:\n")

    count = 0

    # Loop through sorted indices
    for idx in sorted_indices:

        title = df.iloc[idx]["title"]

        # Skip duplicates
        if title in recommended_titles:

            continue

        recommended_titles.add(title)

        instructor = str(df.iloc[idx]["instructor"])

        platform = str(df.iloc[idx]["platform"])

        rating = df.iloc[idx]["rating"]

        url = df.iloc[idx]["url"]

        # Clean formatting
        instructor = instructor.replace("[", "").replace("]", "").replace("'", "")

        platform = platform.replace("[", "").replace("]", "").replace("'", "")

        print("Title:", title)

        print("Instructor:", instructor)

        print("Rating:", rating)

        print("Platform:", platform)

        print("URL:", url)

        print("-" * 50)

        count += 1

        # Stop after top_n
        if count >= top_n:

            break

In [ ]:
recommend_courses("rag")

NameError: name 'model' is not defined

In [ ]:
recommend_courses("Retrieval Augmented Generation")

In [ ]:
model = SentenceTransformer(
    'all-MiniLM-L6-v2'
)

# Generate embeddings
course_embeddings = model.encode(

    df["combined_features"].tolist(),

    show_progress_bar=True
)

print(course_embeddings.shape)

# Semantic recommendation function
# Semantic recommendation function
def recommend_courses_(user_input):

    # Query embedding
    query_embedding = model.encode([user_input])

    # Similarity
    similarity_scores = cosine_similarity(

        query_embedding,

        course_embeddings
    )

    # Flatten
    similarity_scores = similarity_scores.flatten()

    # Add similarity column
    df["similarity"] = similarity_scores

    # Convert ratings
    df["rating"] = pd.to_numeric(
        df["rating"],
        errors="coerce"
    ).fillna(0)

    # English filter
    filtered_df = df[
        df["title"].str.contains(
            r'^[A-Za-z0-9\s:,&()\-]+$',
            regex=True,
            na=False
        )
    ]

    # Similarity threshold
    filtered_df = filtered_df[
        filtered_df["similarity"] > 0.35
    ]

    # Remove duplicates
    filtered_df = filtered_df.drop_duplicates(
        subset=["title"]
    )

    # -----------------------------------
    # TOP RATED COURSES
    # -----------------------------------

    top_rated_courses = filtered_df.sort_values(

        by=["similarity", "rating"],

        ascending=False
    ).head(5)

    # Remove top rated from related list
    remaining_courses = filtered_df[
        ~filtered_df["title"].isin(
            top_rated_courses["title"]
        )
    ]

    # -----------------------------------
    # ALL RELATED COURSES
    # -----------------------------------

    all_related_courses = remaining_courses.sort_values(

        by="similarity",

        ascending=False
    ).head(20)

    return top_rated_courses, all_related_courses

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Batches:   0%|          | 0/272 [00:00<?, ?it/s]

(8695, 384)

In [ ]:
recommend_courses_("machine learning by Jon Reifschneider")

(                                                  title  rating  \
 1993  Machine Learning: Theory and Hands-on Practice...     3.7
 1830  Machine Learning Foundations for Product Managers     4.6
 2027         Machine Learning Introduction for Everyone     4.5
 5034                      Machine Learning: an overview     4.4
 2217  Machine Learning Foundations: A Case Study App...     4.6

                    level                     duration          review  \
 1993  Intermediate level  3 months at 10 hours a week      39 reviews
 1830      Beginner level     15 hours (approximately)     303 reviews
 2027      Beginner level  Approx. 7 hours to complete     192 reviews
 5034      Beginner level      2 hours (approximately)      41 reviews
 2217                         18 hours (approximately)  13,358 reviews

                                             description  \
 1993  Explore several classic Supervised and Unsuper...
 1830
 2027  Compare and contrast artificial intelligence, ...
 5034  Classify machine learning problems, supervised...
 2217

                                                  skills  \
 1993  ['Unsupervised Learning', 'Python Programming'...
 1830  ['Modeling', 'Predictive Analytics', 'Data Sci...
 2027  ['Artificial Intelligence (AI)', 'Reinforcemen...
 5034                                                 []
 2217  ['Python Programming', 'Machine Learning Conce...

                                                 modules  \
 1993  ['Introduction to Machine Learning: Supervised...
 1830  ['What is Machine Learning', 'The Modeling Pro...
 2027  ['Machine Learning for Everyone', 'Machine Lea...
 5034  ['Week 1 - Supervised Learning', 'Week 2 - Uns...
 2217  ['Welcome', 'Regression: Predicting House Pric...

                                   instructor  \
 1993                          ['Geena Kim ']
 1830                   ['Jon Reifschneider']
 2027  ['Aije Egwaikhide', 'Yasmine Hemmati']
 5034                   ['Marcello Restelli']
 2217        ['Emily Fox', 'Carlos Guestrin']

                                 platform                category  \
 1993  ['University of Colorado Boulder']        Computer Science
 1830                 ['Duke University']        Computer Science
 2027                             ['IBM']        Computer Science
 5034           ['Politecnico di Milano']  Information Technology
 2217        ['University of Washington']        Computer Science

                                                     url  \
 1993  https://www.coursera.org/specializations/machi...
 1830  https://www.coursera.org/learn/machine-learnin...
 2027  https://www.coursera.org/learn/machine-learnin...
 5034  https://www.coursera.org/learn/machine-learnin...
 2217      https://www.coursera.org/learn/ml-foundations

                                       combined_features  similarity
 1993  machine learning theory and hands on practice ...    0.489017
 1830  machine learning foundations for product manag...    0.476368
 2027  machine learning introduction for everyone com...    0.471009
 5034  machine learning an overview classify machine ...    0.468618
 2217  machine learning foundations a case study appr...    0.462328  ,
                                                   title  rating  \
 2393         Guided Tour of Machine Learning in Finance     3.8
 2565      IBM Machine Learning Professional Certificate     4.6
 8407  Machine Learning Under the Hood: The Technical...     4.9
 6649  Interpretable machine learning applications: P...     0.0
 1756  IBM Introduction to Machine Learning Specializ...     4.7
 1848    Fundamentals of Machine Learning for Healthcare     4.8
 3718  Machine Learning in Healthcare: Fundamentals &...     0.0
 2698  Supervised Machine Learning: Regression and Cl...     4.9
 5584        Machine Learning: Concepts and Applications     3.3
 2371  Introduction to Machine Learning: Supervised L...     3.3
 1730                           Machine Learning for All     4.7
 1751                    AI in Healthcare Specialization     4.7
 1558  Data Science: Statistics and Machine Learning ...     4.6
 2651         Perform data science with Azure Databricks     3.4
 2278                          Machine Learning Capstone     4.4
 1784              Structuring Machine Learning Projects     4.8
 2558             Applied Data Science for Data Analysts     4.5
 1738        IBM AI Engineering Professional Certificate     4.5
 1501                    Machine Learning Specialization     4.9
 2566  Statistical Learning for Data Science Speciali...     0.0

                    level                      duration          review  \
 2393  Intermediate level      24 hours (approximately)     660 reviews
 2565  Intermediate level   3 months at 10 hours a week   1,491 reviews
 8407      Beginner level      17 hours (approximately)      64 reviews
 6649      Beginner level                     1.5 hours
 1756  Intermediate level   2 months at 10 hours a week     298 reviews
 1848      Beginner level      14 hours (approximately)     379 reviews
 3718      Beginner level  Approx. 18 hours to complete
 2698      Beginner level      33 hours (approximately)  16,959 reviews
 5584  Intermediate level  Approx. 37 hours to complete      13 reviews
 2371  Intermediate level      39 hours (approximately)      43 reviews
 1730      Beginner level  Approx. 21 hours to complete   3,326 reviews
 1751      Beginner level   1 months at 10 hours a week   1,348 reviews
 1558  Intermediate level   3 months at 10 hours a week     586 reviews
 2651  Intermediate level      25 hours (approximately)      45 reviews
 2278  Intermediate level      18 hours (approximately)      45 reviews
 1784      Beginner level       6 hours (approximately)  49,563 reviews
 2558  Intermediate level      16 hours (approximately)      46 reviews
 1738  Intermediate level   2 months at 10 hours a week   5,939 reviews
 1501      Beginner level   2 months at 10 hours a week  19,808 reviews
 2566  Intermediate level    4 months at 9 hours a week

                                             description  \
 2393
 2565  Master the most up-to-date practical skills an...
 8407  Participate in the application of machine lear...
 6649   Be acquainted with the basics of the Aequitas...
 1756  Understand the potential applications of machi...
 1848  Define important relationships between the fie...
 3718
 2698  Build machine learning models in Python using ...
 5584
 2371  Use modern machine learning tools and python l...
 1730  You will understand the basic of how modern ma...
 1751  Identify problems healthcare providers face th...
 1558  Perform regression analysis, least squares and...
 2651  Harness the power of Apache Spark and powerful...
 2278  Compare and contrast different machine learnin...
 1784
 2558  Explore data using unsupervised machine learni...
 1738  Describe machine learning, deep learning, neur...
 1501  Build ML models with NumPy & scikit-learn, bui...
 2566  Express why Statistical Learning is important ...

                                                  skills  \
 2393                                                 []
 2565  ['Ensemble Learning', 'Linear Regression', 'Ma...
 8407  ['Predictive Analytics', 'Artificial Intellige...
 6649  ['Software Engineering', 'Artificial Intellige...
 1756  ['Unsupervised Learning', 'Machine Learning', ...
 1848                                                 []
 3718                                                 []
 2698  ['Linear Regression', 'Regularization to Avoid...
 5584  ['Unsupervised Learning', 'Artificial Neural N...
 2371  ['Hyperparameter', 'sklearn', 'ensembling', 'D...
 1730                                                 []
 1751                                                 []
 1558  ['Github', 'Machine Learning', 'Data Visualiza...
 2651  ['Microsoft Azure', 'Machine Learning', 'Data ...
 2278  ['Artificial Neural Network', 'Data Analysis',...
 1784  ['Decision-Making', 'Machine Learning', 'Deep ...
 2558  ['Data Science', 'Machine Learning', 'Databric...
 1738  ['Image Processing', 'Artificial Intelligence ...
 1501  ['Logistic Regression', 'Artificial Neural Net...
 2566  ['Unsupervised Learning', 'Resampling', 'regre...

                                                 modules  \
 2393  ['Artificial Intelligence & Machine Learning',...
 2565  ['Exploratory Data Analysis for Machine Learni...
 8407  ['MODULE 1 - The Foundational Underpinnings of...
 6649                             ['Learn step-by-step']
 1756  ['Exploratory Data Analysis for Machine Learni...
 1848  ['Why machine learning in healthcare?', 'Conce...
 3718  ['Demystifying Data Mining and Artificial Inte...
 2698  ['Week 1: Introduction to Machine Learning', '...
 5584  ['Machine Learning and the Machine Learning Pi...
 2371  ['Introduction to Machine Learning, Linear Reg...
 1730  ['Machine learning', 'Data Features', 'Machine...
 1751  ['Introduction to Healthcare', 'Introduction t...
 1558  ['Statistical Inference', 'Regression Models',...
 2651  ['Introduction to Azure Databricks', 'Working ...
 2278  ['Capstone Overview', 'Exploratory Data Analys...
 1784                   ['ML Strategy ', 'ML Strategy ']
 2558  ['Welcome to the Course', 'Applied Unsupervise...
 1738  ['Machine Learning with Python', 'Introduction...
 1501  ['Supervised Machine Learning: Regression and ...
 2566  ['Regression and Classification', 'Resampling,...

                                              instructor  \
 2393                                  ['Igor Halperin']
 2565  ['Xintong Li', 'Artem Arutyunov', 'Mark J Grov...
 8407                                    ['Eric Siegel']
 6649                         ['Epaminondas Kapetanios']
 1756  ['Xintong Li', 'Mark J Grover', 'Svitlana (Lan...
 1848                ['Serena Yeung', 'Matthew Lungren']
 3718                   ['Sonya Makhni', 'Paul Cerrato']
 2698  ['Geoff Ladwig', 'Aarti Bagul', 'Eddy Shyu', '...
 5584                              ['Dr. Nick Feamster']
 2371                                     ['Geena Kim ']
 1730                             ['Prof Marco Gillies']
 1751  ['Mildred Cho', 'Steven Bagley', 'Tina Hernand...
 1558  ['Brian Caffo, PhD', 'Jeff Leek, PhD', 'Roger ...
 2651                                     [' Microsoft']
 2278                     ['Artem Arutyunov', 'Yan Luo']
 1784  ['Younes Bensouda Mourri', 'Kian Katanforoosh'...
 2558     ['Mark Roepke', 'Kevin Coyle', 'Emma Freeman']
 1738  ['SAEED AGHABOZORGI', 'Samaya Madhavan', 'Jose...
 1501  ['Geoff Ladwig', 'Aarti Bagul', 'Eddy Shyu', '...
 2566                  ['James Bird', 'Osita Onyejekwe']

                                         platform              category  \
 2393                     ['New York University']      Computer Science
 2565                                     ['IBM']           DataScience
 8407                                     ['SAS']       Social Sciences
 6649                ['Coursera Project Network']  Personal Development
 1756                                     ['IBM']      Computer Science
 1848                     ['Stanford University']      Computer Science
 3718                ['Northeastern University ']                Health
 2698  ['DeepLearning.AI', 'Stanford University']           DataScience
 5584               ['The University of Chicago']        Math and Logic
 2371          ['University of Colorado Boulder']      Computer Science
 1730                    ['University of London']      Computer Science
 1751                     ['Stanford University']      Computer Science
 1558                ['Johns Hopkins University']      Computer Science
 2651                               ['Microsoft']           DataScience
 2278                                     ['IBM']      Computer Science
 1784                         ['DeepLearning.AI']      Computer Science
 2558                              ['Databricks']           DataScience
 1738                                     ['IBM']      Computer Science
 1501  ['Stanford University', 'DeepLearning.AI']      Computer Science
 2566          ['University of Colorado Boulder']           DataScience

                                                     url  \
 2393  https://www.coursera.org/learn/guided-tour-mac...
 2565  https://www.coursera.org/professional-certific...
 8407  https://www.coursera.org/learn/machine-learnin...
 6649  https://www.coursera.org/projects/interpretabl...
 1756  https://www.coursera.org/specializations/ibm-i...
 1848  https://www.coursera.org/learn/fundamental-mac...
 3718  https://www.coursera.org/learn/machine-learnin...
 2698    https://www.coursera.org/learn/machine-learning
 5584  https://www.coursera.org/learn/machine-learnin...
 2371  https://www.coursera.org/learn/introduction-to...
 1730  https://www.coursera.org/learn/uol-machine-lea...
 1751  https://www.coursera.org/specializations/ai-he...
 1558  https://www.coursera.org/specializations/data-...
 2651  https://www.coursera.org/learn/perform-data-sc...
 2278  https://www.coursera.org/learn/machine-learnin...
 1784  https://www.coursera.org/learn/machine-learnin...
 2558  https://www.coursera.org/learn/applied-data-sc...
 1738  https://www.coursera.org/professional-certific...
 1501  https://www.coursera.org/specializations/machi...
 2566  https://www.coursera.org/specializations/stati...

                                       combined_features  similarity
 2393  guided tour of machine learning in finance art...    0.454070
 2565  ibm machine learning professional certificate ...    0.445372
 8407  machine learning under the hood the technical ...    0.437607
 6649  interpretable machine learning applications pa...    0.435112
 1756  ibm introduction to machine learning specializ...    0.427623
 1848  fundamentals of machine learning for healthcar...    0.424331
 3718  machine learning in healthcare fundamentals ap...    0.421485
 2698  supervised machine learning regression and cla...    0.414681
 5584  machine learning concepts and applications uns...    0.413077
 2371  introduction to machine learning supervised le...    0.410230
 1730  machine learning for all you will understand t...    0.408783
 1751  ai in healthcare specialization identify probl...    0.408538
 1558  data science statistics and machine learning s...    0.407075
 2651  perform data science with azure databricks har...    0.406074
 2278  machine learning capstone compare and contrast...    0.404164
 1784  structuring machine learning projects decision...    0.399449
 2558  applied data science for data analysts explore...    0.398919
 1738  ibm ai engineering professional certificate de...    0.398913
 1501  machine learning specialization build ml model...    0.396655
 2566  statistical learning for data science speciali...    0.391328  )

In [ ]:
with open("course_embeddings.pkl", "wb") as f:

    pickle.dump(course_embeddings, f)

In [ ]:
model = SentenceTransformer(
    'all-MiniLM-L6-v2'
)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [ ]:
df.to_csv("final_courses.csv", index=False)